[package]
name = "surreal-rust-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
jsonwebtoken = "8.2.0"
pwhash = "1.0.0"
surrealdb = "1.0.0-beta.8"
